version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather-app
    container_name: weather-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: weather-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - weather-app-network

  nginx:
    image: nginx:latest
    container_name: weather-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    networks:
      - weather-app-network

  db:
    image: mysql:8.0
    container_name: weather-app-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: weather-app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - weather-app-network

networks:
  weather-app-network:
    driver: bridge

volumes:
  dbdata:
